name: Docker Image CI

on:
  push:
    tags:
      - "cjk-**"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Switch to the repository root
      run: cd $GITHUB_WORKSPACE

    - name: Execute build script
      env: 
        RELEASE_VERSION: ${{ github.ref_name }}
      run: |
        echo "Tag name is "$RELEASE_VERSION
        chmod +x ./build_cjk.sh
        ./build_cjk.sh
